# Generated by Django 5.0.6 on 2024-06-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=100)),
                ('volume', models.IntegerField()),
                ('setor', models.CharField(max_length=250)),
            ],
        ),
    ]
