# Generated by Django 5.0.6 on 2024-06-22 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analisador', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ativos',
            new_name='Ativo',
        ),
    ]
