# Generated by Django 5.0.6 on 2024-06-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisador', '0002_rename_ativos_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisadorAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=100)),
                ('volume', models.IntegerField()),
                ('dh_consullta', models.DateTimeField()),
                ('preco', models.FloatField()),
            ],
        ),
    ]
